[project]
name = "c318-frontend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.5.2",
    "matplotlib>=3.10.7",
    "plotly>=6.4.0",
    "scikit-learn>=1.7.2",
    "shap>=0.49.1",
    "streamlit>=1.51.0",
]
